### ISSUE TITLE
pymongo has no attribute Connection

### ISSUE THREAD

**Issue by sonofmun** [DH14/aufschreirevisited#1]
When running the third cell in the first notebook, on the line 

```
con = pymongo.Connection('127.0.0.1', port=27017)
```

I get the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-3795bf90e50a> in <module>()
----> 1 con = pymongo.Connection('127.0.0.1', port=27017)
      2 aufschrei = con.aufschreirevisited.tweets

AttributeError: 'module' object has no attribute 'Connection'
```

**Comment by katsel** [comment]
It's fixed now.

**Comment by sonofmun** [comment]
What did you have to do to fix this?

**Comment by katsel** [comment]
The pymongo package was updated and several function names have changed (see https://api.mongodb.org/python/current/python3.html). I replaced the old function call by "MongoClient()".
